/**
 * Intent Pipeline — shared types.
 * @module pipeline/intent.types
 */

/** Fixed enum of all classifiable intents. */
export type IntentLabel =
  | 'write_file'
  | 'read_file'
  | 'list_files'
  | 'delete_file'
  | 'execute_command'
  | 'chat'
  | 'unknown';

/** How the classification was resolved. */
export type ClassifySource = 'heuristic' | 'llm' | 'cache' | 'context';

/** Result of the intent classifier. */
export interface ClassifyResult {
  intent: IntentLabel;
  confidence: number;
  source: ClassifySource;
}

/** Params for write_file. */
export interface WriteParams {
  path: string;
  content: string;
}

/** Params for read_file. */
export interface ReadParams {
  path: string;
}

/** Params for list_files. */
export interface ListParams {
  path: string;
  depth: number;
}

/** Params for delete_file. */
export interface DeleteParams {
  path: string;
}

/** Params for execute_command. */
export interface ExecuteParams {
  command: string;
  cwd?: string;
}

/** Discriminated union of extracted parameters per intent. */
export type ExtractedParams =
  | { intent: 'write_file'; params: WriteParams }
  | { intent: 'read_file'; params: ReadParams }
  | { intent: 'list_files'; params: ListParams }
  | { intent: 'delete_file'; params: DeleteParams }
  | { intent: 'execute_command'; params: ExecuteParams }
  | { intent: 'chat' | 'unknown'; params: null };

/** Operational context persisted between turns for a session. */
export interface OperationalContext {
  /** Last file path touched (read, written, or listed). */
  lastFilePath?: string;
  /** Last content generated by the LLM (available for "coloca lá"). */
  lastGeneratedContent?: string;
  /** Raw output of the last tool execution. */
  lastToolOutput?: string;
  /** Intent of the last classified turn. */
  lastIntent?: IntentLabel;
}

/** Final decision returned by runPipeline() to the engine. */
export interface PipelineDecision {
  /** 'execute' = force a tool call; 'chat' = fall through to normal agent dispatch. */
  mode: 'execute' | 'chat';
  /** Tool name to invoke (only when mode = 'execute'). */
  toolName?: string;
  /** Tool arguments (only when mode = 'execute'). */
  toolArgs?: Record<string, unknown>;
  /** Classification metadata (always present for logging). */
  classify: ClassifyResult;
  /** Validation error message when execution was blocked (mode='chat' due to validation). */
  validationError?: string;
}
